### ISSUE TITLE
Invalid string undefined error when producing a message

### ISSUE THREAD

**Issue by jobetdelima** [waldophotos/kafka-avro#27]
Hi,

I've updated this issue (https://github.com/waldophotos/kafka-avro/issues/24 ) with more info.  It's not because the topic is not getting created. It's because of an error in the magic-bytes.js code. Was hoping someone familiar with it would know right off the bat what could be going on.

**Comment by tobinski** [comment]
I have the similar issue. The schema is fetched from the registry and present. But if I try to encode my values I got a InvalidError.

**Comment by tobinski** [comment]
I could resolve the issue in my case. I used Union types in my schema. I have the following schema in the kafka schema registry
```javascript
const schema = {
  type: 'record',
  namespace: 'com.example',
  name: 'testvalues',
  fields: [
    {name: 'name', type: ['null', 'string'], default: null}
]};
```
The producer successfully fetches the schema from the registry and failed to encode the value. I  passed the value like this: `const value = {name: "test"};`. This fails. I needed to wrap the value with the correct type: `const value =  { name: {"string": "test"}}`

After I wrapped the UnionTypes I was able to produce data to a topic. On the avcs repo https://github.com/mtth/avsc/issues/20, https://github.com/mtth/avsc/issues/16 you can find some discussion about this topic. Since avcs [v4](https://github.com/mtth/avsc/releases/tag/4.0.0) it should be possible to use Unions more naturally without a wrapping object. But it seems not to work if we call type.encode function directly

**Comment by usopan** [comment]
Any plans to update this repo with v4 avsc?

**Comment by thanpolas** [comment]
> Any one figured out why wrapping is required to correctly parse the union types?

It's just the way union types have been implemented in node.js by avro

**Comment by usopan** [comment]
But if parseOptions.wrapUnions is set to true, it should be handled by the library itself? 
Also if that doesn't work how can I get  Avro type from a Kafka-avro instance? So that I can use wrapUnions method on our own.

**Comment by tobinski** [comment]
You just need to set the parseOptions.wrapUnions to false. Then it should work withoput wrapping values. The option is passed to [avcs](https://github.com/mtth/avsc/wiki/API#typeforschemaschema-opts)
