### ISSUE TITLE
Avro validation on a version of schema

### ISSUE THREAD

**Issue by mayukuse24** [waldophotos/kafka-avro#52]
Hey,

I was unable to find a way to validate the message against a specific version of a schema, which is not the latest one. Is there currently a way to do so using the confluent schema-registry either using the version id or schema id? 

Edit: 

Something like using a [resolver](https://github.com/mtth/avsc/wiki/Advanced-usage#schema-evolution) for 2 different versions of a schema as asked [here](https://github.com/mtth/avsc/issues/168)

**Comment by ricardohbin** [comment]
Hi @mayukuse24 

Actually the lib doesn't support this, but it is not hard to implement this. I will try to add this feature soon :)

**Comment by manikawnth-abg** [comment]
Actually the logic is present to handle different id in case of different versions, but it looks like there's an issue with this code. 
Using `fetchAllVersions` you should be able to fetch all the versions of the schema Registry.

The fetching logic works this way:
1. Fetch the latest schema, register it
2. Fetch all the schemas, one-by-one, and register those
3. In the registering logic, it parses schema using the `avro.parse()` . *This is where the issue is*

```javascript
function typeFromSchemaResponse(schema, parseOptions) {
  var schemaType = avro.parse(schema);

  //check if the schema has been previouisly parsed and added to the registry
  if(typeof parseOptions.registry === 'object' && typeof parseOptions.registry[schemaType.name] !== 'undefined'){
    return parseOptions.registry[schemaType.name]; //ISSUE
  }

  return avro.parse(schema, parseOptions);
}
```

The `avsc` library uses a local registry based on `schemaType.name`  which unfortunately will be same for each topic (key/value + topicName) even though it has different versions.
A decent hack is not to let that caching happen. If you bypass that registry check, avsc library throws a warning and fetches whatever is there in the registry, ultimately **not** solving the purpose.
Hence if you `delete  parseOptions.registry[schemaType.name];` once you do the schema parsing, you should be able to register schema for each version (i.e. `id`)

```javascript
  //check if the schema has been previouisly parsed and added to the registry
  if(typeof parseOptions.registry === 'object' && typeof parseOptions.registry[schemaType.name] !== 'undefined'){
    delete parseOptions.registry[schemaType.name]; //You can't just skip it. You got to delete it
  }
```

@ricardohbin I don't know if it makes sense for you to delete it, atleast in the case of `fetchAllVersions:true` .

**Comment by ricardohbin** [comment]
Hmmm makes sense. For real, the entire schema registry component need to be rewrited, using the same strategy that other libs use (first request on the fly in schema registry, cache it), but I am very busy at work.

If you need this behavior, feel free to open a PR.

**Comment by thanpolas** [comment]
Just a note around why schemas are all pre-fetched, the requirement was for the library to be able to process spiking loads on any given set of topics. 

Due to the nature of kafka, a service could get huge amounts of data in a single moment, it is well established that kafka's throughput can't be matched. The service handling the burst should start processing immediately. Having to wait for a roundtrip to the schema-registry while a stream of messages keeps piling up increases the chances of crashing the server and definitely creates a bottleneck that can propagate way beyond the moment it takes to dynamically fetch the schema from the SR.

That was the reason why schemas are pre-cached before the service becomes operational.
