### ISSUE TITLE
are stream callbacks synchronous?

### ISSUE THREAD

**Issue by mariam-japaridze** [waldophotos/kafka-avro#54]
We have implemented kafka-avro in a platform, which handles over million events a day. During e2e tests, we found out that even though our callback functions are async operations, some events do not wait for callback to be finished and we get wrong calculations.
Are callbacks parallelized? Any help appreciated.

**Comment by thanpolas** [comment]
@mariam-japaridze can you provide implementation examples so we understand which API you are using and the use-case? 

What do you mean "events do not wait for callback to be finished"? If you are referring to consumers, that's the expected behavior, there is no throttling or queueing going on in kafka-avro, consumer callbacks are invoked the moment a message comes in.

**Comment by mariam-japaridze** [comment]
Thank you for your answer. Yes, I am referring to consumers, something like 

stream.on('data', (rawData) => {
      consumer(rawData);  //handles async operations like updates database etc.
 });

Is there a way to make callbacks dependent on each other? Imagine a leaderboard which needs to be iterated constantly or dropped according to data received, If there are  parallel callbacks, we might get wrong results. Any ideas how can we manage this issue?

**Comment by mariam-japaridze** [comment]
I used librdkafka wrappings for python and php in the past, difference was it did not use streams, but while true loop to fetch events. This guaranteed to only consume one event at a time. I understand that for most cases, it's even better to parallelize and use callbacks, but in our case, things are bit different :( Are streams bad idea in this case?
